--- 
title: "Introduction to Data Visualization"
author: "Nathan Garrett, PhD CPA"
date: "Refreshed `r Sys.Date()`"
output: 
  html_document:
    theme: united

---

This document goes with the in-class slide presentation titled "Introduction to Data Visualization"

# Channels

We can map numbers to different visual channels (also called pre-attentive attributes).

- Position on a common scale
- Position on unaligned scale
- Length
- Tilt
- Area
- Color luminescence or brightness
- Color saturation or intensity
- Curvature
- Volume: one of the least accurate approaches
- Depth (3D): generally is best to avoid

In accuracy,

1. Position (common scale, then stacked, and unaligned)
1. Length (unstacked, then stacked)
1. Angle (for pie charts)
1. Area (rectangular is slightly better than circular)


# Storytelling

Compare the mean (x) versus residuals (difference between mean and actual value).


Distributions can be normal (bell curve) or uniform (equally distributed), or skewed (more small or large). 
They can also have an increasing or decreasing spread. 
An outlier can throw off a pattern.
Bimodal means that you have 2 normal curves overlapped. 
Categorical data shows up at only certain spots. 
