--- 
title: "Tableau"
output: 
  html_document:
    theme: united

---

# Installation

Before class, install Tableau on your computer:

- Download the [latest version of Tableau Desktop](https://www.tableau.com/tft/activation)
- Click on the link above and select “Download Tableau Desktop”. On the form, enter your school email address for Business E-mail and enter the name of your school for Organization.
- Activate with your product key:  *See eCampus for key*
- Already have a copy of Tableau Desktop installed? Update your license in the application: Help menu → Manage Product Keys. Make sure that you are fully up to date with the latest version.



# Get Data

Connect to data and get an overview of the interface.
[Shared files](https://www.dropbox.com/sh/l6i1d6z77fgfhk5/AAC3SpND0bK3Nvtv89pQy3wAa?dl=0)

Outcomes:

- Connect to Excel or flat file (csv)
- Differentiate between live, extracts, and packaged files
- Split a field (auto and custom split)
- Connect multiple tables with relationship (including a self-join)
- Pivot wide to tall data
- Rename fields

Examples:
- See Data Prep Flights sample


# Basic charts



Outcomes:

- Describe the difference between discrete and continuous data
  - Understand how date data can be shown
- Understand the difference between aggregate and non-aggregate data
  - Pick an appropriate aggregate function (cnt, median, mean, ...)
- Filter data
- Bar Chart:
  - Sort by name or data
  - Color by dimension or measure
- Heat map
  - Choose function and color
- Scatterplot
  - Show either aggregated or disaggregated data
- Histogram
  - Set a custom bin size
- Boxplot
- Annotations
  - Annotate mark, point, or area
- Formatting
  - Group fields together and give them an alias
  - Choose different measure functions (avg, cnt, etc...)
  - Choose a custom color scale
  - Set custom axis intervals and labels


## Basic Charts 2


Outcomes:

- Use different markings (such as color, shape, label) for information.
- Expand / set a date to year, quarter, month, and date.
- Maps
  - Use either a point or a fill format
  - Understand the difference between long/lat coordinates provided in the dataset,
    vesus those created by Tableau.
  - Create a dual-axis map
  - Set background layers (including Tableau's built-in data layers)
- Combo Chart
  - Use the Dual Axis option to combine a line and bar chart

## Calculations

- Formula Calculations
  - IF THEN 
  - NZ
  - SUM() - or + SUM()
  - Datediff
- Table Calculations
  - Create a running total

## Dashboard / Stories

- Publish to Tableau Public
- Create a dashboard
  - Combine multiple charts together
  - Add a shared filter
- Create a story


# Good resources

- [What is life like as a Tableau Freelancer?](https://www.reddit.com/r/tableau/comments/1724zdf/six_years_as_a_tableau_freelancer_ama/)