--- 
title: "Tableau - Analying Data"
output: 
  html_document:
    theme: united

---

Ask a manager data

https://github.com/rfordatascience/tidytuesday/blob/master/data/2021/2021-05-18/readme.md


Horror Movies
https://github.com/tashapiro/horror-movies/tree/main
https://github.com/rfordatascience/tidytuesday/tree/master/data/2022/2022-11-01


Data:

National Parks - https://github.com/rfordatascience/tidytuesday/tree/master/data/2019/2019-09-17
https://fivethirtyeight.com/features/the-national-parks-have-never-been-more-popular/

Big Mac Index - https://github.com/rfordatascience/tidytuesday/blob/master/data/2020/2020-12-22/readme.md

https://www.economist.com/big-mac-index

# Analyzing data in Tableau
 
See Datacamp *Analyzing data in Tableau*


# Data Fixes

- Dimensions v. Measures
  - Know how to drag a field from the measures list to the dimension list.
- Default properties
  - Set default color, number format, and aggregation
- Date can be *either* continuous or discrete
  - *Continuous* groups by time period (i.e, all Jan 2020, Feb 2020, March 2020, ..., Jan 2021, Feb 2021, etc...)
  - *Discrete* splits into groups (i.e., Jan 2020 & 2021, Feb 2020-2021, March 2020-2021)
  - Suggested using lines for continuous and bars for discrete dates
- Group data
  - Group using Tableau's features
  - Group using SQL / joins and a sub-table
  - Select map dots and group them. 
    - Add/Remove a point to an  existing group 
    - Rename groups
    - Edit the group field
  - Create a custom group sort
## Advanced data fixes



## Advanced fixes

- Connect multiple tables with relationship (including a self-join)
- Pivot wide to tall data
- Set a field to link together two different data sources by clicking on the linking field

## Calculated field
  
-  Create a new calculated field with math (i.e., hours to minutes)
- Functions
  - `DATEDIFF()`
  - `DATEPART()`
  - `IF X = 1 THEN 1 ELSE 2 END`
  - `DIV()`
  - `NZ()`
  - `SUM()`
- Examples
  - Find age from birth-date
- Bin
  - Create a bin size


## Quick table calculation

- Create a quick table calculation 
  - Function (i.e., running total, difference, percent of total)
  - Direction (across, down etc..)
  - Scope (i.e, group)
- Useful items
  - Add a rank, and use it to select top n items in a filter
  - Create a running total
  - Show a field as a percent of the total row or column

## Parameters / Sets

- Set
  - Define a subset and show a division between IN and OUT. You can only use for 2 settings, either TRUE or FALSE. Use a group for more options.
  - Use a set to highlight color, rename, etc..
- Parameter
  - Create a parameter, and a custom range
  - Add a filter using the parameter
  - Use a parameter in a calculated field
  
  
# Chart Display Options

- Edit an alias for a column
- Add a Highlighter from a field
- Axis
  - Rotate a label
  - Format date/time label
  - Label 
- Fit to entire view
- Exclude null data
  - Exclude a range of data by selecting a range and then excluding
- Edit alias for a field's value
- Format
  - Change size / font /color for a cell
- Hide a an axis  
- Labels
  - Set data value labels font, size, alignment, and marks style
- Tooltip
  - Add measure / dimension field
  - Edit font and layout
  - Add a sub-chart
  

# Maps

Maps rely on long/lat. These can be in a dataset, or calculated by Tableau.

- Data
  - Understand the difference between long/lat coordinates provided in the dataset, versus those created by Tableau
  - Understand why you can't do fill for long/lat, but you can for generated lat/long geographic data
- Create the 4 different types
  - Fill
  - Point
  - Density (includes opacity)
    - Set color / intensity
  - Dual axis
- Zoom
  - Zoom in, out, and pan (`shift` to pan)
  - Search
- Layers
  - Color scheme
  - Set background layers (including Tableau's built-in data layers)
  - Add/remove roads
  




