--- 
title: "R for Business Students"
author: "Nathan Garrett, PhD CPA"
date: "Refreshed `r Sys.Date()`"
output: 
  html_document:
    theme: united

---


This section is for ACCT 426 and BUDA 451 students.

## Prereq skills

- [dv02. File Management](dv02-files.html)


## R - Core language and skills

  - [r01. Introduction to rStudio](r01-intro.html)
  - [r02. Introduction to R's core syntax and types](r02-syntax.html) (Datacamp *Introduction to R*)
  - [r04. Project and Rmd files](r04-project-files.html)
  - [r10. dplyr: select, filter, mutate, arrange, and pipe](r10-dplyr.html)
  - [r11. dplyr: group by, summarise, and join](r11-dplyr-shaping.html)
  - [r12. dplyr: pivot](r12-dplyr-reshaping.html)
  - [r15. Loading data](r15-read.html)
  - [r20. ggplot 1: Introduction](r20-ggplot.html)
  - [r21. ggplot 2: Making plots pretty](r21-ggplot-pretty.html)
  - [r22. ggplot 3: Making maps](r22-ggplot-maps-osm.html)
  - [r30. Conditionals](r30-syntax-conditionals.html) (Datacamp *Intermediate R - Conditionals and Control Flow*)
  - [r31. Loops](r31-syntax-loops.html) (Datacamp *Intermediate R - Loops*)
  - [r32. Functions1](r32-syntax-functions1.html) (Datacamp *Intermediate R - Functions* )
  - [r33. Functions2](r33-syntax-functions2.html) (*List of useful functions* )
  - [r80. Dates](r80-dates.html)

# Statistics and Machine Learning

  - [ml00. Modeling the world](ml00-model.html)
  - [ml01. Statistics Refresher](ml01-statistics.html)
  - [ml02. Machine Learning in Business](ml02-business.html) (Datacamp *Machine Learning for Business*)
  - [ml03. Exploratory Data Analysis in R](ml03-eda.html) (DataCamp *Exploratory Data Analysis in R*)
  - [ml10. Regression 1](ml10-regression1.html) (DataCamp *Introduction to Regression in R*)
  - [ml11. Regression 2](ml11-regression2.html) (DataCamp *Supervised Learning in R: Regression*)
  - [ml40. Unsupervised Learning](ml40-unsupervised.html)
  - [ml50. Supervised Learning](ml50-supervised.html)


# Other useful links

- [dv10. Writing an effective report](dv10-effective-reports.html)
- [Create dashboards in R](https://rstudio.github.io/bslib/index.html)


### Application problem

See [problems on GitHub](https://github.com/profgarrett/course_eda_problems/tree/main/)


# Other tutorials:

- [Regression and other stories](https://www.cambridge.org/highereducation/books/regression-and-other-stories)
- [FastR](https://github.com/matloff/fasteR)
- [R Ladies](https://rladiessydney.org/courses/ryouwithme/03-vizwhiz-1/)
- [Swirl](https://swirlstats.com/)
- [Hands-on with R](https://rstudio-education.github.io/hopr/)
- [Building reproducible analytical pipelines with R](https://raps-with-r.dev/preface.html)