---
title: Setup your local computer
output: 
  html_document:
    toc: true
    theme: united
---

# Introduction

This section introduces you to getting your local computer setup.

If you've taken an R class before, I highly recommend uninstalling both R and RStudio before starting the below instructions.


# Prerequisite: Managing files and folders

Managing your folders and files is a key skill. This page walks you through the major things you should know.

When you save a file, it goes into the hard drive on your computer. This hard drive (called the `C:\` on Windows) organizes files into certain locations, called folders.

All modern systems store your files in several folders:

- `Downloads`: this is supposed to be temporary spot for files downloaded by Safari or Chrome.
- `Desktop`: files/folders visible on your desktop
- `Documents`: where you should store your long-term files

One wrinkle is that Windows often uses OneDrive. OneDrive is an online service that syncs your local files with servers in the Internet. Files are typically still stored on your computer, but are regularly uploaded. So, if you have OneDrive turned on, typically the OneDrive Downloads/Desktop/Documents is the same as the location on your hard drive (usually C:\).


Organize your files: [link to video on YouTube](https://www.youtube.com/watch?v=gfPujXtQqwc)

Here is a quick guide for organizing your files, slightly more focused on the Mac. [link to video on YouTube](https://www.youtube.com/watch?v=gfx7G4NQQMg)


## Making folders {.tabset}

You should have a folder for our class. Then, create a folder for each week or major project. Store your files inside of this folder.


### Make a folder on PC

Right-click in a folder, and choose `New folder` (or press `Control+Shift+N`)

<iframe width='640' height='572' src="https://www.youtube.com/embed/Amd6V-ERLO8" data-external= "1" allowfullscreen> </iframe>
[link to video on YouTube](https://www.youtube.com/watch?v=Amd6V-ERLO8)

### Make a folder on Mac

Right-click in a folder, and choose `New Folder`

<iframe width='640' height='572' src="https://www.youtube.com/embed/xPVOaFmQ7_s" data-external= "1" allowfullscreen> </iframe>

[link to video on YouTube](https://www.youtube.com/watch?v=xPVOaFmQ7_s)

## Moving files {.tabset}

Avoid modifying any files in your download folder. Instead, download them, and then copy them to the appropriate folder.

### Move files on a PC

Guide to using Files Explorer on Windows.

<iframe width='640' height='572' src="https://www.youtube.com/embed/hXLpEG3IX-A" data-external= "1" allowfullscreen> </iframe>
[link to video on YouTube](https://www.youtube.com/watch?v=hXLpEG3IX-A)

### Move files on a Mac

I suggest disabling the Force touch feature:

- Use the Apple menu to open `System Preferences`
- Click `Trackpad`, the `Point & Click` tab
- Turn off `Force click and haptic feedback` 


Right-click on a file, right-click copy, go to the new place, and click paste. 
Or, move a file by opening a separate `Finder` window, and dragging/dropping your files.

<iframe width='640' height='572' src="https://www.youtube.com/embed/gFKJpkpDcwo" data-external= "1" allowfullscreen> </iframe>
[link to video on YouTube](https://www.youtube.com/watch?v=gFKJpkpDcwo)


## Other setup

One more thing that would be helpful in our class is to turn on file extensions. This will tell you the hidden information that lives in ever file's name. So, when you save a Word document as `my stuff`, it actually is saved as `my stuff.docx`. The `.docx` tells the computer to open the file in Word.

As we work with more complex files, you will find that you can not just click on a file to open it in the right program. Instead, get in the habit of opening a program first. Then, inside of the program, open the file (usually by going to the file menu and choosing open).

To turn on:

- Open Windows Explorer
- Open View menu
- Show submenu
- File Name Extensions


# Installing R

- Install R: https://cran.rstudio.com/
  - Install R Studio: https://www.rstudio.com/products/rstudio/download/
- Configure R
  - Go to Tools / Global Options and set General / Basic options
    -  Disable *restore most recently opened project at startup*
    -  Disable *Restore .RData into Workspace on startup*
    -  Set *Save Workspace to .RData on exit* to never
    -  Disable *Always save history*
  - Set Code / Diagnostics
    -  Turn on all diagnostics except *warn if variable used has no definition in scope*
  - Show markers
    - Go to *View / *Show Other Panes* / *Show Markers*
  - lintr
    - For more specific style guides, install lintr
    - Go to  Tools > addins > Browse Addins > Keyboard Shortcuts and set the Control + Shift + L keyboard shortcut
    - Note that you have to save the file before running the linter. 


# RStudio

- RStudio features
  - Console for interactive input
  - Script editor for saving (be sure to re-run)
  - Shortcuts: control+enter to run the current line, or all selected.
- Files Management


Do not depend on program state or .RData files! I must be able to run your code as it is submitted in the R file. I strongly suggest closing and re-opening R, and then running all of the code to make sure it works properly.


## Shortcuts

There are several vital shortcuts:

- *alt -* for `<-` 
- *control s* for saving 
- *control shift l* for linter (always save first!)
- *control enter* to run the current line or highlighted section


# Application Problem

See [problems on GitHub](https://github.com/profgarrett/course_eda_problems/tree/main/r01-intro)