---
title: Useful Functions
output: 
  html_document:
    toc: true
    theme: united
---

# Introduction

There are a variety of useful functions in R. Below is a brief listing

## Math functions

- `median()`/`mean()`/`max()`/`min()`/`sum()`
- `abs()` - absolute value
- `round()` - rounds 1.2 to 1
- `seq(from, to, increment)` - returns a sequence from -> to (skipping every increment)
- `rep(x, times)` - return a new vector of x, repeated *times*. 

In the readr library:

- `readr::parse_integer()`: turns "1" into 1

## Text functions

- `paste0(text1, text2, ...)`: combine text values
- `paste(text1, text2, ..., sep = ',' )`: combines text, split with sep

## Tables

- `View(data)`: opens data in a nice gui. Note that it is capitalized!
- `names(data)`: what are the field names of the data?

## Vectors/Lists

- `sort()`/`rev()`: order items in a vector 
- `vector_a <- append(vector_a, new_item_or_vector_of_items)`: create a new vector with the additional items
- `unlist()`: turn a list into a vector

## Graphics

- `plot()`: create a basic x/y plot

## Statistics

- `table()`: create a crosstab
- `cor()`: calculate correlation

## Types

- `is_*()`: test for types (convert * to integer, etc...)
- `as_*()`: convert a type



### Application problem

See [problems on GitHub](https://github.com/profgarrett/course_eda_problems/tree/main/r33-syntax-functions2)
