---
title: Statistics Refresher
output: 
  html_document:
    toc: true
    theme: united
---

# Introduction

# Statistics Refresher


## Normal distribution

Outcomes: 

- Describe the concept of a normal distribution
- Describe why having a normal distribution is useful
- List some items having (or not) a normal distribution

Help: https://www.youtube.com/watch?v=3VYupIsbLlY


## Correlation 

Outcomes:

- Describe the role of a correlation
- Describe why we sometimes use r^2 insead of r?

Help: https://www.youtube.com/watch?v=rijqfllOq6g

## Linear Regression

Outcomes:

- Describe when using a linear regression model is useful
- Describe dependent and independent variables
- Describe linear and non-linear relationships
- Transform inputs to meet various requirements


Terms:

- Coefficients 
- Residuals, sse (sum of squares error / loss function)
- Bias / intercept
- R^2

Help: https://www.youtube.com/watch?v=3dhcmeOTZ_Q


## Logistic Refression

Outcomes:

- When do we use logistic regression?
- Interpret a confusion matrix

Help: https://www.youtube.com/watch?v=EKm0spFxFG4
